### ISSUE TITLE
Wrong instruction in the readme file

### ISSUE THREAD

**Issue by scagnoni** [martafdezmAM/lessen_supervision#1]
In the readme file you suggest to change directory before running the scripts using the 'mv' command

'mv' moves files from one directory to another (as such , it requires two parameters, source and destination, so the instruction you tell readers to use generates an error)

Use the 'change directory' ('cd') command instead

Stefano Cagnoni

**Comment by martafdezmAM** [comment]
Thank you very much for the correction, I have just updated the readme. It was a typical copy-paste error from a previous project. 

Marta Fernandez
